/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CurrentAffairsRouteImport } from './routes/current-affairs'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as AnswerWritingIndexRouteImport } from './routes/answer-writing.index'
import { Route as AnswerWritingPromptIdRouteImport } from './routes/answer-writing.$promptId'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as SettingsAiRouteImport } from './routes/settings.ai'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsDataRouteImport } from './routes/settings.data'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as VaultIndexRouteImport } from './routes/vault.index'
import { Route as VaultImagesRouteImport } from './routes/vault.images'
import { Route as VaultPdfsRouteImport } from './routes/vault.pdfs'
import { Route as VaultSavedRouteImport } from './routes/vault.saved'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentAffairsRoute = CurrentAffairsRouteImport.update({
  id: '/current-affairs',
  path: '/current-affairs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerWritingIndexRoute = AnswerWritingIndexRouteImport.update({
  id: '/answer-writing/',
  path: '/answer-writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerWritingPromptIdRoute = AnswerWritingPromptIdRouteImport.update({
  id: '/answer-writing/$promptId',
  path: '/answer-writing/$promptId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAiRoute = SettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/settings/appearance',
  path: '/settings/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/settings/data',
  path: '/settings/data',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/vault/',
  path: '/vault/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultImagesRoute = VaultImagesRouteImport.update({
  id: '/vault/images',
  path: '/vault/images',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultPdfsRoute = VaultPdfsRouteImport.update({
  id: '/vault/pdfs',
  path: '/vault/pdfs',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultSavedRoute = VaultSavedRouteImport.update({
  id: '/vault/saved',
  path: '/vault/saved',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/exams': typeof ExamsRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/answer-writing/$promptId': typeof AnswerWritingPromptIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/vault/images': typeof VaultImagesRoute
  '/vault/pdfs': typeof VaultPdfsRoute
  '/vault/saved': typeof VaultSavedRoute
  '/answer-writing/': typeof AnswerWritingIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/vault/': typeof VaultIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/exams': typeof ExamsRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/answer-writing/$promptId': typeof AnswerWritingPromptIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/vault/images': typeof VaultImagesRoute
  '/vault/pdfs': typeof VaultPdfsRoute
  '/vault/saved': typeof VaultSavedRoute
  '/answer-writing': typeof AnswerWritingIndexRoute
  '/notes': typeof NotesIndexRoute
  '/vault': typeof VaultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/exams': typeof ExamsRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/answer-writing/$promptId': typeof AnswerWritingPromptIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/vault/images': typeof VaultImagesRoute
  '/vault/pdfs': typeof VaultPdfsRoute
  '/vault/saved': typeof VaultSavedRoute
  '/answer-writing/': typeof AnswerWritingIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/vault/': typeof VaultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/current-affairs'
    | '/exams'
    | '/plan'
    | '/progress'
    | '/answer-writing/$promptId'
    | '/notes/$noteId'
    | '/settings/ai'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/vault/images'
    | '/vault/pdfs'
    | '/vault/saved'
    | '/answer-writing/'
    | '/notes/'
    | '/vault/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/current-affairs'
    | '/exams'
    | '/plan'
    | '/progress'
    | '/answer-writing/$promptId'
    | '/notes/$noteId'
    | '/settings/ai'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/vault/images'
    | '/vault/pdfs'
    | '/vault/saved'
    | '/answer-writing'
    | '/notes'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/current-affairs'
    | '/exams'
    | '/plan'
    | '/progress'
    | '/answer-writing/$promptId'
    | '/notes/$noteId'
    | '/settings/ai'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/vault/images'
    | '/vault/pdfs'
    | '/vault/saved'
    | '/answer-writing/'
    | '/notes/'
    | '/vault/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CurrentAffairsRoute: typeof CurrentAffairsRoute
  ExamsRoute: typeof ExamsRoute
  PlanRoute: typeof PlanRoute
  ProgressRoute: typeof ProgressRoute
  AnswerWritingPromptIdRoute: typeof AnswerWritingPromptIdRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  SettingsAiRoute: typeof SettingsAiRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  VaultImagesRoute: typeof VaultImagesRoute
  VaultPdfsRoute: typeof VaultPdfsRoute
  VaultSavedRoute: typeof VaultSavedRoute
  AnswerWritingIndexRoute: typeof AnswerWritingIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  VaultIndexRoute: typeof VaultIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-affairs': {
      id: '/current-affairs'
      path: '/current-affairs'
      fullPath: '/current-affairs'
      preLoaderRoute: typeof CurrentAffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer-writing/': {
      id: '/answer-writing/'
      path: '/answer-writing'
      fullPath: '/answer-writing/'
      preLoaderRoute: typeof AnswerWritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer-writing/$promptId': {
      id: '/answer-writing/$promptId'
      path: '/answer-writing/$promptId'
      fullPath: '/answer-writing/$promptId'
      preLoaderRoute: typeof AnswerWritingPromptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/ai': {
      id: '/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/settings/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/': {
      id: '/vault/'
      path: '/vault'
      fullPath: '/vault/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/images': {
      id: '/vault/images'
      path: '/vault/images'
      fullPath: '/vault/images'
      preLoaderRoute: typeof VaultImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/pdfs': {
      id: '/vault/pdfs'
      path: '/vault/pdfs'
      fullPath: '/vault/pdfs'
      preLoaderRoute: typeof VaultPdfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/saved': {
      id: '/vault/saved'
      path: '/vault/saved'
      fullPath: '/vault/saved'
      preLoaderRoute: typeof VaultSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CurrentAffairsRoute: CurrentAffairsRoute,
  ExamsRoute: ExamsRoute,
  PlanRoute: PlanRoute,
  ProgressRoute: ProgressRoute,
  AnswerWritingPromptIdRoute: AnswerWritingPromptIdRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  SettingsAiRoute: SettingsAiRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  VaultImagesRoute: VaultImagesRoute,
  VaultPdfsRoute: VaultPdfsRoute,
  VaultSavedRoute: VaultSavedRoute,
  AnswerWritingIndexRoute: AnswerWritingIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  VaultIndexRoute: VaultIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
